---
- name: Install basic infrastructure for all the projects
  hosts: digital-ocean
  user: root
  tasks:
    - name: cleaning up apt
      command: apt-get -y autoremove

    - name: setting up the folder
      command: mkdir -p /root/deployments/ins_data_viz

    - name: setting up the archives folder
      command: mkdir -p /root/archives/ins_data_viz

    - name: uploading tarball with the project
      copy: src=../build/ins_data_viz.tar.gz dest=/root/archives/ins_data_viz.tar.gz

    - name: untaring the project
      command: tar -xvf /root/archives/ins_data_viz.tar.gz -C /root/deployments/ins_data_viz

    - name: installing bundler
      command: bash -lc "gem install bundler"

    - name: getting the gems (maybe i should not be doing this in prod)
      command: bash -lc "bundle install"
      args:
        chdir: /root/deployments/ins_data_viz

    - name: uploading unicorn config
      copy: src=files/unicorn.rb dest=/root/deployments/ins_data_viz

    - name: uploading service conf
      copy: src=files/ins_data_viz.conf dest=/etc/init/ins_data_viz.conf

    - name: restarting the unicorn service
      service: name=ins_data_viz state=restarted

    - name: uploading nginx conf
      copy: src=files/app_nginx.conf dest=/etc/nginx/sites-available/ins_data_viz.conf

    - name: uploading nginx conf
      copy: src=files/app_nginx.conf dest=/etc/nginx/sites-enabled/ins_data_viz.conf

    - name: uploading nginx logstash conf
      template: src=files/nginx.logstash.conf dest=/etc/logstash/conf.d/02-nginx.conf

    - name: restarting the nginx service
      service: name=nginx state=restarted

    - name: Ensure filebeat process is stopped and disabled.
      service: name=filebeat state=stopped enabled=no

  vars:
    logstash_elasticsearch_hosts:
      - https://logsene-receiver.sematext.com:443
    sematext_token: "{{ lookup('env','SEMATEXT_TOKEN') }}"


  roles:
    - redis
    - kbrebanov.ruby
    - geerlingguy.nginx
    - geerlingguy.java
    - geerlingguy.logstash
