---

# Filebeat user and group
#  WARNING: If you run filebeat with a user other than root make sure
#  your logs are readable by the filebeat user. Add the filebeat user
#  to a privileged group, with access to your logs (adm)
filebeat_user:  root
filebeat_group: root

# Create the filebeat user and group
filebeat_create_user: true

# Filebeat version to use
# 
filebeat_version: 1.1.1

# Filebeat Solaris url
#
# filebeat_solaris_url: {{http://<url_to_your_pkg>/filebeat-{{ filebeat_version }}-solaris-amd64.pkg


# Start filebeat at boot time
#
filebeat_start_at_boot: True

# Filebeat version upgrade
#  This options allows package upgrades. 
#  Make sure you know what this implies.
filebeat_upgrade: false

filebeat_config_file: /etc/filebeat/filebeat.yml

filebeat_config_registry_file: /var/lib/filebeat/registry

# Filebeat configuration
#  The configuratlion is built based on a single variable, in YAML format, filebeat_config.
#  Just for fun and example, it has been splitted into multiple vars:
#
#   - filebeat_config_prospectors
#   - filebeat_config_output
#   - filebeat_config_shipper
#   - filebeat_config_logging
#

filebeat_config_prospectors: |
  filebeat:
    prospectors:
      -
        input_type: log
        paths:
          - /var/log/*.log
        registry_file: "{{filebeat_config_registry_file}}"


filebeat_config_output: |
  output:
    elasticsearch:
      hosts: [ 'localhost:9200' ]


filebeat_config_shipper: |
  shipper:


filebeat_config_logging: |
  logging:
    files:
      rotateeverybytes: 10485760 # = 10MB


filebeat_config: |
  {{filebeat_config_prospectors}}

  {{filebeat_config_output}}

  {{filebeat_config_shipper}}

  {{filebeat_config_logging}}

filebeat_use_apt_repo: True

# List of template files to copy 
filebeat_templates: []

# vi:ts=2:sw=2:et:ft=yaml

