---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  become: true
  tags: filebeat_install

- include: config.yml
  become: true
  tags: filebeat_config

- include: template.yml
  become: true
  tags: filebeat_template

- name: Ensure Filebeat is enabled and started at boot
  service:
    name: filebeat
    enabled: yes
    state: started
  when: filebeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
